version: "3.8"

services:
  djangle:
    build: .
    env_file:
      - .env
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    volumes:
      - ./:/app
    depends_on:
      - postgres
    command: python mysite/manage.py runserver 0.0.0.0:${DJANGO_PORT}

  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
